{{- if and (not .Values.postgres.enabled) (not (and .Values.postgres.settings.existingSecret .Values.postgres.userDatabase.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}-postgres
data:
  db: {{ .Values.postgres.userDatabase.name.value | b64enc }}
  dbuser: {{ .Values.postgres.userDatabase.user.value | b64enc }}
  dbuserpw: {{ .Values.postgres.userDatabase.password.value | b64enc }}
  superuserpw: {{ .Values.postgres.settings.superuserPassword.value | b64enc }}
{{- end }}
