apiVersion: v1
kind: Service
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}-flask
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
    app.kubernetes.io/component: flask
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "sketch-map-tool.selectorLabels" . | nindent 4 }}
