apiVersion: v1
kind: Service
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}-flower
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    {{- include "sketch-map-tool.selectorLabels" . | nindent 4 }}
