kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
