name: smt
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - poetry=1.7.*
  - gdal=3.7.1
  - zbar=0.10  # dependency of pyzbar
  - psycopg2=2.9.6
  - pip:
    # bypass issue related to Mac OS and psycopg2-binary
    - psycopg2-binary==2.9.5
    # bypass venv issue related to nushell
    - virtualenv==20.7
