# Default values for sketch-map-tool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

celery:
  image:
    repository: repo.example.org/smt
    tag: latest

flask:
  image:
    repository: repo.example.org/smt
    tag: latest

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  # -- Expose flask via gateway-api HTTPRoute
  # Requires Gateway API resources and suitable controller installed within the cluster
  # (see: https://gateway-api.sigs.k8s.io/guides/)
  httpRoute:
    # HTTPRoute enabled.
    enabled: false
    # HTTPRoute annotations.
    annotations: {}
    # Which Gateways this Route is attached to.
    parentRefs:
      - name: gateway
        sectionName: http
        # namespace: default
    # Hostnames matching HTTP header.
    hostnames:
      - chart-example.local
    # List of rules and filters applied.
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

flower:
  image:
    repository: repo.example.org/smt
    tag: latest
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  # -- Expose flower via gateway-api HTTPRoute
  # Requires Gateway API resources and suitable controller installed within the cluster
  # (see: https://gateway-api.sigs.k8s.io/guides/)
  httpRoute:
    # HTTPRoute enabled.
    enabled: false
    # HTTPRoute annotations.
    annotations: {}
    # Which Gateways this Route is attached to.
    parentRefs:
      - name: gateway
        sectionName: http
        # namespace: default
    # Hostnames matching HTTP header.
    hostnames:
      - chart-example.local
    # List of rules and filters applied.
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

# Configuration for the volume that holds the weights
persistence:
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # storageClassName:

postgres:
  # When enabled groundhog2k/postgres helm chart is deployed along side the SketchMapTool. Set to false when using your own Postgres database in- or outside of Kubernetes.
  # For full values see here https://artifacthub.io/packages/helm/groundhog2k/postgres?modal=values
  enabled: true
  # When postgres.enabled is false set the address of your external postgres DB here
  # connectionString:
  settings:
    ## Optional existing secret for the Postgrest superuser
    # existingSecret:
    superuserPassword:
      # secretKey:
      value: smtpgadminpw
  userDatabase:
    ## Optional existing secret with database name, user and password
    # existingSecret:
    name:
      # secretKey:
      value: smt
    user:
      # secretKey:
      value: smtuser
    password:
      # secretKey:
      value: smtuserpw
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  customConfig: |
    # Generated with https://pgtune.leopard.in.ua/
    # DB Version: 17
    # OS Type: linux
    # DB Type: web
    # Total Memory (RAM): 1 GB
    # Data Storage: ssd

    max_connections = 200
    shared_buffers = 256MB
    effective_cache_size = 768MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 7864kB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 1260kB
    huge_pages = off
    min_wal_size = 1GB
    max_wal_size = 4GB
  storage:
    requestedSize: 100Gi
    # className:

redis:
  # When enabled groundhog2k/redis helm chart is deployed along side the SketchMapTool. Set to false when using your own redis cache in- or outside of Kubernetes.
  # For full values see here https://artifacthub.io/packages/helm/groundhog2k/redis?modal=values
  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  storage:
    requestedSize: 10Gi
    # className:
