@startuml
package "Sketch Map Tool" {
  node webclient as "Web App Frontend" <<JavaScript>> {
      component client as "Client"
    }

    node flask as "Web App Backend" <<Flask>> {
        component routes.py
    }

    node celery as "Task Queue" <<Celery>>{
        component tasks.py
        component oqt_analyses
        component map_generation
        component upload_processing
        tasks.py --> oqt_analyses
        tasks.py --> map_generation
        tasks.py --> upload_processing
    }

    database postgres as "Result Store" <<Postgres>>
    database redis as "Message Broker" <<Redis>>

    routes.py --> tasks.py
    flask -> postgres
    celery --> redis
    celery --> postgres
    client --> routes.py
}

cloud internet as "Internet" #line.dotted

package "HeiGIT Maps" #line.dotted {
    cloud wms as "Web Map Server (WMS)" #line.dotted
    database osmdb as "OpenStreetMap Database (OSMDB)" #line.dotted

}

package "HeiGIT ohsome Framework" #line.dotted {
    cloud oqt as "ohsome quality API" #line.dotted
    cloud ohsome as "ohsome API" #line.dotted
}

package "ESRI World Imagery (Satellite Imagery)" #line.dotted {
    cloud arcgis as "ArcGIS REST API" #line.dotted
}

internet --> client

map_generation --> wms : Map Image
wms --> osmdb
wms --> arcgis

oqt_analyses --> oqt : Quality Report
oqt --> ohsome
@enduml
