name: Unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update package lists
        run: sudo apt-get update
      - name: Install system dependencies (gdal freetype and zbar)
        run: sudo apt-get install -y --fix-missing libgdal-dev libfreetype6-dev libzbar0
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install python dependencies
        run: |
          poetry install
      - name: Install gdal as python package
        run: |
          poetry run pip install gdal=="$(gdal-config --version).*"
      - name: Run unit tests
        run: |
          poetry run pytest tests/unit
